<?php

namespace AKYOS\BackofficeBundle\Repository;

/**
 * SyndicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyndicRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSyndicByCoproprietaire($coproprietaire){

        $qb = $this->createQueryBuilder('s')
            ->JOIN('s.coproprietes','sc')
            ->JOIN('sc.lots', 'scl')
            ->JOIN('scl.coproprietaires', 'c')
            ->where('c = :coproprietaire')
            ->setParameter('coproprietaire',$coproprietaire);

            return $qb->getQuery()->getSingleResult();
    }
}
