<?php

namespace AKYOS\EasyCoproBundle\Repository;

/**
 * ArtisanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtisanRepository extends \Doctrine\ORM\EntityRepository
{
}
