<?php

namespace AKYOS\EasyCoproBundle\Repository;

/**
 * CoproprietaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoproprietaireRepository extends \Doctrine\ORM\EntityRepository
{
}
