<?php

namespace AKYOS\EasyCoproBundle\Repository;

/**
 * CoproprieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoproprieteRepository extends \Doctrine\ORM\EntityRepository
{
}
