<?php

namespace AKYOS\EasyCoproBundle\Repository;

/**
 * CoproprieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoproprieteRepository extends \Doctrine\ORM\EntityRepository
{
    public function find3LastCoproprietesBySyndic($syndic){

        $query = $this->createQueryBuilder('c')
            ->where('c.syndic = :syndic')
            ->setParameter('syndic', $syndic)
            ->orderBy('c.dateDebutGestion', 'desc')
            ->setMaxResults(3)
            ->getQuery()
            ->getResult();
        return $query;
    }





}
