<?php

namespace AKYOS\EasyCoproBundle\Repository;

/**
 * CoproprieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoproprieteRepository extends \Doctrine\ORM\EntityRepository
{
    public function find3LastCoproprietesBySyndic($syndic){

        $query = $this->createQueryBuilder('c')
            ->where('c.syndic = :syndic')
            ->setParameter('syndic', $syndic)
            ->orderBy('c.dateDebutGestion', 'desc')
            ->setMaxResults(3)
            ->getQuery()
            ->getResult();
        return $query;
    }

    public function findCoproprieteDocuments($copropriete) {

        $qb = $this->createQueryBuilder('d')
            ->leftJoin('d.lots', 'l')
            ->where('l.copropriete = :copropriete')
            ->setParameter('copropriete', $copropriete)
        ;
        return $qb->getQuery()->getResult();
    }


    /*public function findNbrDocumentsByCopropriete($copropriete){

        $qb = $this->createQueryBuilder('d')
            ->select('COUNT(d)')
            ->innerJoin('d.lots','l')
            ->join('l.copropriete', 'c')
            ->where('c = :copropriete')
            ->setParameter('copropriete', $copropriete)
            ;
        return $qb->getQuery()->getSingleScalarResult();
    }*/

}
