<?php

namespace AKYOS\EasyCoproBundle\Repository;

/**
 * LocataireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocataireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLocataireBySyndic($syndic){

        $qb = $this->createQueryBuilder('l')
            ->select('COUNT(l)')
            ->join('l.lot', 'll')
            ->join('ll.copropriete', 'llc')
            ->join('llc.syndic', 's')
            ->where('s = :syndic')
            ->setParameter('syndic', $syndic);
        return $qb->getQuery()->getSingleScalarResult();
    }
}
