<?php

namespace AKYOS\EasyCoproBundle\Repository;

/**
 * LocataireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocataireRepository extends \Doctrine\ORM\EntityRepository
{
}
