<?php

namespace AKYOS\EasyCoproBundle\Repository;

/**
 * LotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LotRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByCopropriete($copropriete) {
        $qb = $this->createQueryBuilder('l')
            ->select('c.nom, c.prenom')
            ->join('l.coproprietaires', 'c')
            ->where('l.copropriete = :copropriete')
            ->setParameter('copropriete', $copropriete);

        return $qb->getQuery()->getArrayResult();
    }
}
