<?php

namespace AKYOS\EasyCoproBundle\Repository;

/**
 * PostitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostitRepository extends \Doctrine\ORM\EntityRepository
{
}
