<?php

namespace AKYOS\EasyCoproBundle\Repository;

/**
 * SyndicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyndicRepository extends \Doctrine\ORM\EntityRepository
{
}
